[package]
name = "hehir"
version = "0.1.0"
edition = "2021"
authors = ["Hartley McGuire <skipkayhil@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6", features = ['http'] }
worker-macros = { version = "0.6", features = ['http'] }
http = "1.3"
